### ISSUE TITLE
Should I submit pull requests for any of these?

### ISSUE THREAD

**Issue by JustinGOSSES** [ESIPFed/Awesome-Earth-Artificial-Intelligence#1]
Hello, happy to see this. I help admin awesome-open-geoscience that has some overlap but has a subsurface focus. I have a couple suggestions that I'd be happy to help with. 

1. Add a "related awesome" section and add other earth science related awesome lists as seen in [awesome-open-geoscience](https://github.com/softwareunderground/awesome-open-geoscience).
2. Instead of having a separate [link] in blue at end of each instance, have the name at the front be the linked text. This makes it much easier to scan. 
3. Add license file to the repository.
4. Add contributing.md, awesome.md, and code-of-conduct.md files to the repository like in (https://github.com/softwareunderground/awesome-open-geoscience) to set expectations and give people instructions to follow.

**Comment by ZihengSun** [comment]
@JustinGOSSES Thanks! Great advice! Please do. I just watched the awesome-open-geoscience and will check if there is AI-related stuff which can be merged.

**Comment by ZihengSun** [comment]
@JustinGOSSES please check if the new PR addressed this issue, thanks!

**Comment by JustinGOSSES** [comment]
Great work! 

Yes, this knocks out everything. Sorry, this fell off my radar.
